DROP TABLE public."PERSONA";

CREATE TABLE public."PERSONA"
(
  ID_PERSONA SERIAL PRIMARY KEY,
  NOMBRE_PERSONA character varying
)
WITH (
  OIDS=FALSE
);

ALTER TABLE public."PERSONA"
  OWNER TO postgres;


DROP TABLE public."AUTO";
CREATE TABLE public."AUTO"
(
  ID_AUTO SERIAL PRIMARY KEY,
  ID_PERSONA integer NOT NULL,
  MARCA_AUTO character varying(100),
  CONSTRAINT fk_id_persona FOREIGN KEY (id_persona)
      REFERENCES public."PERSONA" (ID_PERSONA) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public."AUTO"
  OWNER TO postgres;

SELECT * FROM public."PERSONA";
SELECT * FROM public."AUTO";

INSERT INTO public."PERSONA"(NOMBRE_PERSONA) VALUES('JUANITO');
INSERT INTO public."PERSONA"(NOMBRE_PERSONA) VALUES('PEDRO');
INSERT INTO public."PERSONA"(NOMBRE_PERSONA) VALUES('MARIA');

INSERT INTO public."AUTO"(ID_PERSONA, MARCA_AUTO) VALUES(1, 'TOYOTA');
INSERT INTO public."AUTO"(ID_PERSONA, MARCA_AUTO) VALUES(1, 'CHEVROLET');
INSERT INTO public."AUTO"(ID_PERSONA, MARCA_AUTO) VALUES(3, 'FERRARI');

SELECT perso.ID_PERSONA, count(auto.*)
FROM public."PERSONA" as perso
LEFT JOIN public."AUTO" as auto
on perso.ID_PERSONA = auto.ID_PERSONA
group by perso.ID_PERSONA
ORDER BY perso.ID_PERSONA;
